### ISSUE TITLE
Feature Request: Add the original 2004-2007 login screen as a configurable option.

### ISSUE THREAD

**Issue by src52** [ndugdale/osrs-web-greeter-theme#4]
Add a configurable option that makes the login screen look like the actual old RuneScape login screen.

![Tumblr_mfix6jOs8Z1rr6167o1_1280](https://user-images.githubusercontent.com/17970489/208742004-da261b49-49ed-4d82-bbd3-bd86c44fd495.jpg)

**Comment by ndugdale** [comment]
Thanks for checking out the project! At this point in time I'm not aware of a method for reading a theme-specific config file when using web-greeter. The alternative is to have a configuration menu in the UI which could be brought up perhaps by a keyboard shortcut. Currently, I don't think this is a solution I will be investigating with any priority.

What exactly would you be looking to customise? Some things I can think of are:
- removing background image arrows
- removing session select button (although this requires you to only use one session type)
- flames: this is a separate feature entirely. I think the best way to recreate these faithfully is to reverse engineer the osrs java client code and convert to typescript, which is non-trivial

If you are really keen on hiding some of the buttons without waiting, and aren't looking to quickly convert back and forth between having them and not having them, I'd encourage you to fork the project and add the following CSS property to any react component you wish to hide,
```
visibility: hidden
```

The modified project can then be built and installed using the same instructions under the **Installation** heading in the README.

**Comment by ndugdale** [comment]
I've added a configuration menu, which can be brought up using `Ctrl` + `.`. Not sure if it has all the options you want, but you can hide the session select and background select buttons, as well as change the zoom, which can be used to achieve a full-screen view or cater for HiDPI displays.
